@baseUrl = http://192.168.0.128:3001

GET {{baseUrl}}/user

###  Getting a todo of given id
GET {{baseUrl}}/item

###  Getting a todo of given id
GET {{baseUrl}}/order

### Add new item
POST {{baseUrl}}/item HTTP/1.1
Content-Type: application/json

{
     "name": "CK shirt",
     "brand": "Calvin Klein",
     "image": "assets/images/four.jpg",
     "quantity": 6,
     "price": 100.49,
     "desc": "This is item description for Polo v1",
     "id": 4
}

### Add new item
POST {{baseUrl}}/order HTTP/1.1
Content-Type: application/json

{
      "id": 2,
      "name": "Swagor",
      "brand": "Levis",
      "image": "assets/images/two.jpg",
      "quantity": 6,
      "price": 100.05,
      "desc": "This is item description for Swagor",
      "userid": "OK5T1DrQu02i8tbgngx3",
      "userID": "OK5T1DrQu02i8tbgngx3"
}

### Update the status of a given todo (whether is completed or not)
PATCH {{baseUrl}}/user/ZICXkHsPTy4ZeGQgg8Fm
Content-Type: application/json

{
     "name": "Jasmin"
}

### Update the status of a given todo (whether is completed or not)
PATCH {{baseUrl}}/item/3
Content-Type: application/json

{
     "price": 120.05
}

### Update the status of a given todo (whether is completed or not)
PATCH {{baseUrl}}/item/1
Content-Type: application/json

{
     "userID": "OK5T1DrQu02i8tbgngx3"
}





